version: '3.8'

services:
  macro-bot:
    build: .
    container_name: macro-usd-bot
    restart: unless-stopped
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Volume for persistent data
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    # Network configuration  
    networks:
      - macro-bot-network
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/macro_bot.db').close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  macro-bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local
  bot-logs:
    driver: local